/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import java.awt.Image;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
/**
 *
 * @author Jefferson
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/Img/Fundo.png"));
        Image image = icon.getImage();
        Fundo = new javax.swing.JPanel(){
            public void paintComponent(Graphics g){
                g.drawImage(image, 0, 0, getWidth(), getHeight(), this);
            }
        };
        jPanel1 = new javax.swing.JPanel();
        Título = new javax.swing.JLabel();
        tit_login = new javax.swing.JLabel();
        Login_Usuario = new javax.swing.JTextField();
        Button_Entrar = new javax.swing.JToggleButton();
        Login_Senha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        jPanel1.setBackground(new java.awt.Color(59, 75, 89));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setVerifyInputWhenFocusTarget(false);

        Título.setFont(new java.awt.Font("A25-SQUANOVA", 1, 50)); // NOI18N
        Título.setForeground(new java.awt.Color(242, 163, 94));
        Título.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Título.setText("Contrest");

        tit_login.setBackground(new java.awt.Color(242, 163, 94));
        tit_login.setFont(new java.awt.Font("NewsGoth BT", 0, 24)); // NOI18N
        tit_login.setForeground(new java.awt.Color(255, 153, 51));
        tit_login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tit_login.setText("Login");
        tit_login.setToolTipText("");

        Login_Usuario.setForeground(new java.awt.Color(242, 163, 94));
        Login_Usuario.setText("Login");
        Login_Usuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Login_Usuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Login_UsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Login_UsuarioFocusLost(evt);
            }
        });
        Login_Usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Login_UsuarioMouseClicked(evt);
            }
        });
        Login_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_UsuarioActionPerformed(evt);
            }
        });
        Login_Usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Login_UsuarioKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Login_UsuarioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Login_UsuarioKeyTyped(evt);
            }
        });

        Button_Entrar.setText("Entrar");
        Button_Entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_EntrarActionPerformed(evt);
            }
        });
        Button_Entrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Button_EntrarKeyPressed(evt);
            }
        });

        Login_Senha.setForeground(new java.awt.Color(242, 163, 94));
        Login_Senha.setText("Login");
        Login_Senha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Login_SenhaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Login_SenhaFocusLost(evt);
            }
        });
        Login_Senha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Login_SenhaMouseClicked(evt);
            }
        });
        Login_Senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_SenhaActionPerformed(evt);
            }
        });
        Login_Senha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Login_SenhaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tit_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Título, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(222, 222, 222)
                                .addComponent(Button_Entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Login_Usuario, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Login_Senha))))
                        .addGap(68, 68, 68))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(Título)
                .addGap(29, 29, 29)
                .addComponent(tit_login)
                .addGap(36, 36, 36)
                .addComponent(Login_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(Login_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(Button_Entrar)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout FundoLayout = new javax.swing.GroupLayout(Fundo);
        Fundo.setLayout(FundoLayout);
        FundoLayout.setHorizontalGroup(
            FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FundoLayout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(204, 204, 204))
        );
        FundoLayout.setVerticalGroup(
            FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FundoLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(57, 57, 57))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_EntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_EntrarActionPerformed
        logar();
    }//GEN-LAST:event_Button_EntrarActionPerformed

    private void Login_SenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Login_SenhaMouseClicked
        if(Login_Senha.getText().equals("Login")){
            Login_Senha.setText("");    
        }// TODO add your handling code here:
    }//GEN-LAST:event_Login_SenhaMouseClicked

    private void Login_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Login_UsuarioActionPerformed

    private void Login_UsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Login_UsuarioMouseClicked
        if(Login_Usuario.getText().equals("Login")){
            Login_Usuario.setText("");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_Login_UsuarioMouseClicked

    private void Login_UsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Login_UsuarioFocusGained
    
    }//GEN-LAST:event_Login_UsuarioFocusGained

    private void Login_SenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Login_SenhaFocusGained
       if(Login_Senha.getText().equals("Login")){
            Login_Senha.setText("");      
       }    
    }//GEN-LAST:event_Login_SenhaFocusGained

    private void Login_UsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Login_UsuarioKeyPressed
        if(Login_Usuario.getText().equals("Login")){
            Login_Usuario.setText("");
        }            // TODO add your handling code here:
    }//GEN-LAST:event_Login_UsuarioKeyPressed

    private void Login_UsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Login_UsuarioKeyReleased
           // TODO add your handling code here:
    }//GEN-LAST:event_Login_UsuarioKeyReleased

    private void Login_UsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Login_UsuarioKeyTyped
              // TODO add your handling code here:
    }//GEN-LAST:event_Login_UsuarioKeyTyped

    private void Login_UsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Login_UsuarioFocusLost
        if(Login_Usuario.getText().equals("")){
            Login_Usuario.setText("Login");    
        }    // TODO add your handling code here:
    }//GEN-LAST:event_Login_UsuarioFocusLost

    private void Login_SenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Login_SenhaFocusLost
        if(Login_Senha.getText().equals("")){
            Login_Senha.setText("Login");    
        }          // TODO add your handling code here:
    }//GEN-LAST:event_Login_SenhaFocusLost

    private void Login_SenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_SenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Login_SenhaActionPerformed

    private void Login_SenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Login_SenhaKeyPressed
            if(evt.getKeyCode() == evt.VK_ENTER){
            logar();
        }             // TODO add your handling code here:
    }//GEN-LAST:event_Login_SenhaKeyPressed

    private void Button_EntrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Button_EntrarKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            logar();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_Button_EntrarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Button_Entrar;
    private javax.swing.JPanel Fundo;
    private javax.swing.JPasswordField Login_Senha;
    private javax.swing.JTextField Login_Usuario;
    private javax.swing.JLabel Título;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel tit_login;
    // End of variables declaration//GEN-END:variables

    private void logar (){
        if(Login_Usuario.getText().equals("adm") && Login_Senha.getText().equals("123")){
                JOptionPane dialogo = new JOptionPane();
                JOptionPane.showMessageDialog(null, ""+Login_Usuario.getText()+" logado com sucesso!", "Sucesso!", 1); 
                dialogo.setVisible(true); 

                Func_Menu Menu = new Func_Menu();
                Menu.setVisible(true);

                this.dispose();
            }
            else {
                JOptionPane dialogo = new JOptionPane();
                JOptionPane.showMessageDialog(null, "Revise os dados de Login", "Erro!", ERROR_MESSAGE); 
                dialogo.setVisible(true); 
            }
    }
}
